import type { Metadata } from "next";
import { K2D } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/custom/Headers/Navbar";
import Sidebar from "@/components/custom/Headers/Sidebar";

const k2d = K2D({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={k2d.className}>
        <Navbar />
        <div className="sm:flex sm:justify-center mx-auto">
          <div className="hidden md:block ml-60">
            <Sidebar />
          </div>
          <div className="p-5 w-full md:max-w-[1920px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
